### ISSUE TITLE
Docker migration error

### ISSUE THREAD

**Issue by iQiexie** [egguy/pubcrawl-optimizer#72]
Database doesn't migrate itself on docker startup

```
roman@romans-MacBook-Air pubcrawl-optimizer % docker run -it -v ./local.db --env-file=.env.local -p 3000:3000 pub-crawl-optimizer
Listening on 0.0.0.0:3000
Failed to fetch breweries with tags: LibsqlError: SQLITE_ERROR: no such table: brewery
    at mapSqliteError (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:372:16)
    at executeStmt (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:277:15)
    at Sqlite3Client.execute (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:79:16)
    ... 4 lines matching cause stack trace ...
    at QueryPromise.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17) {
  code: 'SQLITE_ERROR',
  rawCode: 1,
  [cause]: SqliteError: no such table: brewery
      at convertError (/app/node_modules/libsql/index.js:51:12)
      at Database.prepare (/app/node_modules/libsql/index.js:119:13)
      at executeStmt (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:248:28)
      at Sqlite3Client.execute (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:79:16)
      at LibSQLPreparedQuery.values (file:///app/node_modules/drizzle-orm/libsql/session.js:182:59)
      at LibSQLPreparedQuery.all (file:///app/node_modules/drizzle-orm/libsql/session.js:126:29)
      at QueryPromise.executeRaw (file:///app/node_modules/drizzle-orm/sqlite-core/query-builders/query.js:136:33)
      at QueryPromise.execute (file:///app/node_modules/drizzle-orm/sqlite-core/query-builders/query.js:139:17)
      at QueryPromise.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17) {
    code: 'SQLITE_ERROR',
    rawCode: 1
  }
} {
  activeOnly: true,
  tagKeys: [ 'food', 'beer', 'wifi', 'dog', 'vegan', 'vegetarian', 'music' ]
}
LibsqlError: SQLITE_ERROR: no such table: brewery
    at mapSqliteError (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:372:16)
    at executeStmt (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:277:15)
    at Sqlite3Client.execute (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:79:16)
    ... 4 lines matching cause stack trace ...
    at QueryPromise.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17) {
  code: 'SQLITE_ERROR',
  rawCode: 1,
  [cause]: SqliteError: no such table: brewery
      at convertError (/app/node_modules/libsql/index.js:51:12)
      at Database.prepare (/app/node_modules/libsql/index.js:119:13)
      at executeStmt (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:248:28)
      at Sqlite3Client.execute (file:///app/node_modules/@libsql/client/lib-esm/sqlite3.js:79:16)
      at LibSQLPreparedQuery.values (file:///app/node_modules/drizzle-orm/libsql/session.js:182:59)
      at LibSQLPreparedQuery.all (file:///app/node_modules/drizzle-orm/libsql/session.js:126:29)
      at QueryPromise.executeRaw (file:///app/node_modules/drizzle-orm/sqlite-core/query-builders/query.js:136:33)
      at QueryPromise.execute (file:///app/node_modules/drizzle-orm/sqlite-core/query-builders/query.js:139:17)
      at QueryPromise.then (file:///app/node_modules/drizzle-orm/query-promise.js:21:17) {
    code: 'SQLITE_ERROR',
    rawCode: 1
  }
}
```

**Comment by egguy** [comment]
Hi, thanks for taking a look at my software.

I will take a search how to make the production build migrate. For the moment, I copy a pre deployed database in production, so I didn't encounter this problem.

Meanwhile, you can do a `npm run db:push` in your dev env to create a local database, and a `npm run db:studio` will allow you to fill the database with a GUI.

**Comment by iQiexie** [comment]
Ok, thank you!

> Hi, thanks for taking a look at my software.
> 
> I will take a search how to make the production build migrate. For the moment, I copy a pre deployed database in production, so I didn't encounter this problem.
> 
> Meanwhile, you can do a `npm run db:push` in your dev env to create a local database, and a `npm run db:studio` will allow you to fill the database with a GUI.
